# Log record type
RUNPARTITION_RECORD = 0
PROCESS_RECORD = 1
SYNCDONE_RECORD = 2
ASYNCDONE_RECORD = 3
REQUEST_RECORD = 4
DONECALLBACK_RECORD = 5

# Node in graph type
SEND_NODE = 0
RECV_NODE = 1
COMM_NODE = 2
